export const paths = {
  index: "/",
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:email',
  dashboard: "/dashboard",
  emergency: "/emergency",
  profile: "/profile",
  statistics: "/statistics",
  chat: "/chat",
  appointments: "/appointments",
  appointmentDetails: "/appointment/:id",
  invoices: "/invoices",
  invoiceDetails: "/invoice/:id",
  downloadInvoice: "/download-invoice/:id",
  createInvoice: "/create-invoice/:id",
  payments: "/payments",
  chatDetails: "/chat/:id",
  settings: '/settings',
  billing: '/plan-and-billing',
  calendar: '/calendar',
  updateInvoice: '/update-invoice/:id/:invoiceId',
};
