export enum ModalEventKey {
  NOTIFICATION = "NOTIFICATION",
  APPOINTMENT_DETAILS = "APPOINTMENT_DETAILS",
  EDIT_PROFILE = "EDIT_PROFILE",
  STATISTICS_PROFILE = "STATISTICS_PROFILE",
  ADD_PAYPMENT_METHOD = "ADD_PAYMENT",
  WITHDRAW_PAYMENT = "WITHDRAW_PAYMENT",
  OPEN_CALENDAR = "OPEN_CALANDAR",
}
