export enum StateEnum {
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_GARAGE_MANAGER = "ROLE_GARAGE_MANAGER",
    ROLE_SERVICE_MANAGER = "ROLE_SERVICE_MANAGER",
    ROLE_TECHNICIAN = "ROLE_TECHNICIAN",
    ROLE_CUSTOMER = "ROLE_CUSTOMER",
    ROLE_RECEPTIONIST = "ROLE_RECEPTIONIST"
}