export interface UserInterface {
    name: string,
    email: string,
    password: string,
    verifie: string,
    passwordExpir: string,
    dateOfBirth: string,
    profileImageUrl: string,
    profileImageId: string,
    provider: string,
    phones: string,
    role: string,
    permissions: string,
    garages: string,
    verificationCodes: string,
    id: string,
    createdA: string,
    verified: boolean,
    createdAt: string,
    updatedA: string,
    createdB: string,
    updatedBy: string,
    location: {
        latitude: number,
        longitude: number,
        description: string,
        id: string,
        createdBy: string | null,
        updatedBy: string | null,
        createdAt: string | null,
        updatedAt: string | null
    } | null | undefined, 
}
