export enum Permissions {
  READ_SERVICE_CENTER = "READ_SERVICE_CENTER",
  CREATE_SERVICE = "CREATE_SERVICE",
  UPDATE_SERVICE = "UPDATE_SERVICE",
  DELETE_SERVICE_CENTER = "DELETE_SERVICE_CENTER",
  UPDATE_SERVICE_CENTER = "UPDATE_SERVICE_CENTER",
  READ_SERVICE = "READ_SERVICE",
  DELETE_SERVICE = "DELETE_SERVICE",
  CREATE_SERVICE_CENTER = "CREATE_SERVICE_CENTER",
  ASSIGN_ITEM = "ASSIGN_ITEM"
}