name: Build and Deploy Service Center Vite App Docker Image to AWS EC2

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build with Vite
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" == "yarn" ]; then
            yarn build
          else
            npm run build
          fi
          
      - name: Print npm debug log
        run: |
          if [ -f /home/viteuser/.npm/_logs/*.log ]; then
            cat /home/viteuser/.npm/_logs/*.log
          else
            echo "No npm debug log found."
          fi
          
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/service-center:dev .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/service-center:dev

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/service-center:dev

      - name: Delete Old Docker Container
        run: sudo docker rm -f vite-app || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -e VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -p 5173:5173 --name vite-app \
            ${{ secrets.DOCKER_USERNAME }}/service-center:dev

      - name: Print npm debug log
        run: |
          if [ -f /home/viteuser/.npm/_logs/*.log ]; then
            cat /home/viteuser/.npm/_logs/*.log
          else
            echo "No npm debug log found."
          fi
